[package]
name = "ftk"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]
edition = "2018"

[dependencies]
termcolor = "1.0.5"

[dependencies.clap]
version = "2.33.0"
default-features = false

[dependencies.fortknight]
path = "fortknight"

[workspace]
members = ["fortknight"]