[package]
name = "fortknight"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
num-derive = "0.2.5"
num-traits = "0.2.8"
radix_trie = "0.1.4"
termcolor = "1.0.5"
typed-arena = "1.5.0"
peek-nth = "0.2"